<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDcuvco6\EccubeDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDcuvco6/EccubeDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDcuvco6.legacy');

    return;
}

if (!\class_exists(EccubeDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDcuvco6\EccubeDevDebugProjectContainer::class, EccubeDevDebugProjectContainer::class, false);
}

return new \ContainerDcuvco6\EccubeDevDebugProjectContainer([
    'container.build_hash' => 'Dcuvco6',
    'container.build_id' => '913d7e91',
    'container.build_time' => 1599212868,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDcuvco6');
